<a href="https://colab.research.google.com/github/marvillegas16/Herramientas-computacionales/blob/main/3_abril_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
B = np.array ([[1, 2, 3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(B[:,0:1])

[[1]
 [4]]


In [ ]:
print(B[:,0:2])

[[1 2]
 [4 5]]


In [ ]:
print(B[:,::2])

[[1 3]
 [4 6]]


In [ ]:
print(B[::2])

[[1 2 3]]


In [ ]:
b= np.array([1, 2, 3, 4, 5])

In [ ]:
b%2 == 0

array([False,  True, False,  True, False])

In [ ]:
b[b%2 == 0]

array([2, 4])

In [ ]:
b[b>=3]

array([3, 4, 5])

In [ ]:
b

array([1, 2, 3, 4, 5])

In [ ]:
(b < 3) | (b > 3)

array([ True,  True, False,  True,  True])

In [ ]:
def factorial(n):
  fact=1

  for i in range(1,n+1):
    fact=fact*i

  return fact

factorial(5)

120